//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.16 at 02:53:16 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://Ocpp/Cs/2012/06/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ocpp.cs._2012._06;
