developer:

 1. I want be able to add, remove, edit, search the ChargePoint in the system.
  
 2. I want the ChargePoint can receive the message from central system, and response automatically.
  
 3. I want be able to trace the incoming and outgoing messages between the ChargePoint and central system.
  
 4. I want all kinds of ChargePoint, which support OCPP1.5, OCPP1.6 or other protocols.
 
 5. I want the simulator can send  specified messages to a specified URL.
  
  
  